data: data/data.csv

scaling_method: null # Options: "standard", "minmax", or None

tuning_output: results/tuning_results.csv
assignments_output: results/cluster_assignments.csv
classification_output: results/classification_report.csv